### ISSUE TITLE
Question: can assume onelogin user?

### ISSUE THREAD

**Issue by ZsoltPath** [onelogin/onelogin-aws-cli-assume-role#35]
Is it possible to assume a user with this package?
If not, would it be possible to add the feature?

The application would be same as in the web UI.

**Comment by pitbulk** [comment]
it assumes roles. It is similar to: https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html

If you are trying to use aws sso at aws cli, check:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

**Comment by ZsoltPath** [comment]
Sorry, I think I was confusing.

I meant to assume another OL user and then assume the AWS role assigned to that user. As I could do this on the web console.

**Comment by pitbulk** [comment]
This AWS-CLI uses OL API to interact with its services.

In order to retrieve the SAMLResponse to be used at AWS, this API endpoint is used:
https://developers.onelogin.com/api-docs/1/saml-assertions/generate-saml-assertion

and that endpoint requires user username + password (+mfa). So it requires the user to know the other user credentials.

**Comment by ZsoltPath** [comment]
OK. I thought if it's working on one platform, it could work on another.
